seed: 10086

# -------------------------------------------------------------
dataset:
  lmdb_path: "/scratch/yl10337/Content-Style-Disentangled-Representation-Learning/font_latents.lmdb"
  font_json: "/scratch/yl10337/Content-Style-Disentangled-Representation-Learning/lmdb_keys.json"
  train_ratio: 0.9
  latent_size: 16          # 16×16×4 → flatten 1024
  augment_prob: 0.0

# -------------------------------------------------------------
encoder:            # Residual MLP
  input_dim: 1024
  hidden_dim: 2048
  num_layers: 4

denoiser:           # SimpleMLPAdaLN
  model_channels: 2048
  num_res_blocks: 4
  timesteps: 1000
  beta_start: 1e-4
  beta_end: 2e-2
  grad_ckpt: false

# -------------------------------------------------------------
train:
  epochs: 200
  batch_size: 256
  lr: 2.0e-4
  weight_decay: 0.0
  save_interval: 5
  ckpt_dir: "checkpoints/ddpm_disentangle"

eval:
  batch_size: 256
  interval: 5        # 每 5 个 epoch 跑一次验证集

num_workers: 8

wandb:
  enable: false
  project: "font_disentangle_ddpm"
  log_interval: 100