# model
encoder: vae_encoder        # UNet2D encoder-only
decoder: vae_decoder        # UNet2D decoder
latent_dim: [8, 8, 8]       # (C=8, H=8, W=8)

# data
data_root: ./data
img_size: 128

# training
epochs: 5000
batch_size: 32
lr: 0.0001

# loss weights
lpips_weight: 0.8
kl_weight: 0.5
vq_loss_weight: 1.0
use_gan: false 
gan_weight: 0.5

# GAN
use_gan: true
in_channels: 1

# resume
resume_ckpt: ""